"""Renders a per-video analysis into a downloadable PDF case study: cover
page with metadata + key UX insights, then a screen-by-screen flow
walkthrough with the actual extracted frame images.

Runs synchronously (fpdf2 + Pillow are blocking) -- callers should run this
via app.deps.run_cpu, not directly on the event loop.
"""

from datetime import UTC, datetime
from pathlib import Path

from fpdf import FPDF
from PIL import Image

PAGE_WIDTH_MM = 210.0  # A4
MARGIN_MM = 18.0
CONTENT_WIDTH_MM = PAGE_WIDTH_MM - 2 * MARGIN_MM

# The core Helvetica font only supports latin-1, but LLM-generated text
# commonly contains smart punctuation outside that range (fpdf raises
# FPDFUnicodeEncodingException otherwise).
_UNICODE_TO_LATIN1 = {
    "—": "-",  # em dash
    "–": "-",  # en dash
    "‘": "'",  # left single quote
    "’": "'",  # right single quote
    "“": '"',  # left double quote
    "”": '"',  # right double quote
    "…": "...",  # ellipsis
    " ": " ",  # non-breaking space
    "•": "-",  # bullet
}


def _pdf_safe(text: str) -> str:
    for unicode_char, replacement in _UNICODE_TO_LATIN1.items():
        text = text.replace(unicode_char, replacement)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _image_height_for_width(path: Path, width_mm: float) -> float:
    with Image.open(path) as img:
        w, h = img.size
    return width_mm * (h / w)


def _format_duration(seconds: int | None) -> str | None:
    if not seconds:
        return None
    m, s = divmod(int(seconds), 60)
    return f"{m}:{s:02d}"


class _CaseStudyPDF(FPDF):
    title_text: str = ""

    def header(self) -> None:
        if self.page_no() == 1:
            return
        self.set_y(10)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(140, 140, 140)
        self.cell(0, 6, self.title_text[:90])
        self.set_y(20)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(140, 140, 140)
        self.cell(0, 10, f"Page {self.page_no()} - Generated by FlowScope", align="C")


def build_case_study_pdf(
    *,
    video: dict,
    ux_insights: list[str],
    flow_steps: list[dict],
    frames_by_id: dict[str, dict],
    output_path: Path,
) -> None:
    pdf = _CaseStudyPDF(format="A4")
    pdf.title_text = _pdf_safe(video.get("title") or "Untitled product demo")
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(MARGIN_MM, MARGIN_MM, MARGIN_MM)
    pdf.set_title(pdf.title_text)

    # --- Cover ---
    pdf.add_page()
    pdf.set_y(30)
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(20, 20, 20)
    pdf.multi_cell(CONTENT_WIDTH_MM, 11, pdf.title_text, align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 13)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, "Competitive UX Case Study", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    pdf.set_font("Helvetica", "", 10.5)
    pdf.set_text_color(70, 70, 70)
    duration = _format_duration(video.get("duration_seconds"))
    meta_lines = []
    if video.get("channel"):
        meta_lines.append(f"Channel: {video['channel']}")
    if duration:
        meta_lines.append(f"Duration: {duration}")
    if video.get("youtube_url"):
        meta_lines.append(f"Source: {video['youtube_url']}")
    meta_lines.append(f"Generated: {datetime.now(UTC).strftime('%Y-%m-%d')} via FlowScope")
    for line in meta_lines:
        pdf.set_x(MARGIN_MM)
        pdf.multi_cell(CONTENT_WIDTH_MM, 6, _pdf_safe(line), new_x="LMARGIN", new_y="NEXT")

    if ux_insights:
        pdf.ln(10)
        pdf.set_font("Helvetica", "B", 15)
        pdf.set_text_color(20, 20, 20)
        pdf.cell(0, 9, "Key UX Insights", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 10.5)
        pdf.set_text_color(45, 45, 45)
        for insight in ux_insights:
            pdf.set_x(MARGIN_MM)
            pdf.multi_cell(CONTENT_WIDTH_MM, 6, _pdf_safe(f"-  {insight}"), new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1.5)

    # --- Flow walkthrough ---
    if flow_steps:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 17)
        pdf.set_text_color(20, 20, 20)
        pdf.cell(0, 10, "Product Flow Walkthrough", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

        for step in sorted(flow_steps, key=lambda s: s.get("step_index", 0)):
            frame = frames_by_id.get(step.get("frame_id"))
            image_path = Path(frame["file_path"]) if frame else None
            img_h = 0.0
            if image_path and image_path.exists():
                img_h = _image_height_for_width(image_path, CONTENT_WIDTH_MM)

            estimated_height = img_h + 32
            if pdf.get_y() + estimated_height > pdf.h - pdf.b_margin:
                pdf.add_page()

            pdf.set_font("Helvetica", "B", 12.5)
            pdf.set_text_color(20, 20, 20)
            step_title = f"{step.get('step_index', '?')}. {step.get('screen_name', 'Untitled screen')}"
            pdf.set_x(MARGIN_MM)
            pdf.multi_cell(CONTENT_WIDTH_MM, 7, _pdf_safe(step_title), new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1.5)

            if image_path and image_path.exists():
                pdf.image(str(image_path), x=MARGIN_MM, w=CONTENT_WIDTH_MM)
                pdf.ln(2)

            transcript_excerpt = (frame or {}).get("transcript_excerpt")
            if transcript_excerpt:
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(90, 90, 90)
                pdf.set_x(MARGIN_MM)
                pdf.cell(0, 5, "NARRATION AT THIS MOMENT", new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Helvetica", "I", 9.5)
                pdf.set_text_color(75, 75, 75)
                pdf.set_x(MARGIN_MM)
                pdf.multi_cell(
                    CONTENT_WIDTH_MM,
                    5.5,
                    _pdf_safe(f'"{transcript_excerpt}"'),
                    new_x="LMARGIN",
                    new_y="NEXT",
                )
                pdf.ln(2)

            pdf.set_font("Helvetica", "", 10.5)
            pdf.set_text_color(60, 60, 60)
            pdf.set_x(MARGIN_MM)
            pdf.multi_cell(CONTENT_WIDTH_MM, 6, _pdf_safe(step.get("description", "")), new_x="LMARGIN", new_y="NEXT")
            pdf.ln(7)

    pdf.output(str(output_path))
